library(distill)
library(postcards)

create_article('blog')
create_post("Introducción a Visualizaciones con R")
create_post("Introducción a Visualizaciones con Python")
create_post("aprender git")
create_post("CheatSheet SQL")
create_post("Agile inception")
create_post("adalab workshop python")
create_post("AWS Copilot")
create_post("Data Quality")
create_post("Spotify Methodology")
create_post("Spotify Methodology-2")
create_post("Data Quality",collection ="posts_en")
create_post("AWS Copilot",collection ="posts_en")
create_post("Agile inception",collection ="posts_en")
create_post("rabbitmq-pika",collection ="posts_en")
create_post("Code Quality - SonarQube",collection ="posts_en")
create_post("SQL to Python Pandas: A SQL User's Quick Guide",collection ="posts_en")
create_post("Decoding a Data Model - Using SchemaSpy in Snowflake",collection ="posts_en")
create_post("Transform your Pandas Dataframes",collection ="posts_en")


