library(distill)
library(postcards)

create_article('blog')
create_post("Introducción a Visualizaciones con R")
create_post("Introducción a Visualizaciones con Python")
create_post("aprender git")
create_post("CheatSheet SQL")
create_post("Agile inception")
create_post("adalab workshop python")
create_post("AWS Copilot")
create_post("Data Quality")
create_post("Spotify Methodology")